### ISSUE TITLE
l will not set

### ISSUE THREAD

**Issue by coco66688** [ckt1031/DraconianBot#11]
If you are not using .env supported hosters, please add code require('dotenv').config() to the top of the code from index.js, shard.js and other place are needed to use process.env.(stuff)

**Comment by coco66688** [comment]
@RealKoolisw 
help

**Comment by TeunHessels** [comment]
wat host are you using i can help if your using repl.it

**Comment by Blaketherank** [comment]
I'm using relp.it i need help
