### ISSUE TITLE
Need Help It Says An Error

### ISSUE THREAD

**Issue by ghost** [ckt1031/DraconianBot#12]
`Fontconfig error: Cannot load default config file
(node:4163) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (/home/runner/DraconianJSBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:133:26)
    at Client.login (/home/runner/DraconianJSBot/node_modules/discord.js/src/client/Client.js:223:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4163) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4163) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[DisTube] Downloaded youtube-dl 2021.03.14
(node:4156) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (/home/runner/DraconianJSBot/node_modules/discord.js/src/sharding/Shard.js:163:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:4156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by compteccharan** [comment]
Where Am I wrong ?
https://replit.com/join/szilqerd-comptechcharan
am coding in repl.it could U help

**Comment by ghost** [comment]
hmm I found myself
however thanks for ur code I am learning more deep with other repos

**Comment by ghost** [comment]
bye
