### ISSUE TITLE
Status  :- How to change the status of that bot ?

### ISSUE THREAD

**Issue by hirishav** [ckt1031/DraconianBot#13]
Please help me

**Comment by Darker-Ink** [comment]
> Please help me

First I suggest learning discord.js and JavaScript before trying to host a bot and 2nd its in events/client/ready.js

**Comment by tzt345** [comment]
> Please help me

[Go Here ;)](https://github.com/RealKoolisw/DraconianJSBot/blob/main/events/client/ready.js)
