### ISSUE TITLE
Porbleme

### ISSUE THREAD

**Issue by arthurcorso** [ckt1031/DraconianBot#15]
quand je lance mon bot sa mes sa

`PS C:\Users\ZeGamer.c\Desktop\DraconianJSBot-main> node shard.js
Command Loaded setprefix.js
Command Loaded 8ball.js
Command Loaded meme.js
Command Loaded poke.js
Command Loaded reverse.js
Command Loaded smug.js
Command Loaded snipe.js
Command Loaded tickle.js
Command Loaded gend.js
Command Loaded greroll.js
Command Loaded gstart.js
Command Loaded cat.js
Command Loaded changemymind.js
Command Loaded circle.js
Command Loaded clyde.js
Command Loaded delete.js
Command Loaded gay.js
Command Loaded kiss.js
Command Loaded ngif.js
Command Loaded pat.js
Command Loaded petpet.js
Command Loaded rip.js
Command Loaded spank.js
Command Loaded trigger.js
Command Loaded channel.js
Command Loaded help.js
Command Loaded ping.js
Command Loaded roleinfo.js
Command Loaded send-image.js
Command Loaded serverinfo.js
Command Loaded setafk.js
Command Loaded stats.js
Command Loaded uptime.js
Command Loaded vote.js
Command Loaded whois.js
Command Loaded ban.js
Command Loaded clear.js
Command Loaded clearwarn.js
Command Loaded createchannel.js
Command Loaded createemoji.js
Command Loaded kick.js
Command Loaded lockchannel.js
Command Loaded mute.js
Command Loaded rename.js
Command Loaded slowmode.js
Command Loaded unban.js
Command Loaded unlockchannel.js
Command Loaded unmute.js
Command Loaded warn.js
Command Loaded warnings.js
Command Loaded autoplay.js
Command Loaded jumpto.js
Command Loaded loop.js
Command Loaded pause.js
Command Loaded play.js
Command Loaded queue.js
Command Loaded resume.js
Command Loaded skip.js
Command Loaded stop.js
Command Loaded volume.js
Command Loaded 4knsfw.js
Command Loaded anal.js
Command Loaded ass.js
Command Loaded hentai.js
Command Loaded holo.js
Command Loaded porn.js
Command Loaded pussy.js
Command Loaded thigh.js
Command Loaded urban.js
Command Loaded wallpaper.js
Command Loaded reload.js
Command Loaded reset-database.js
Command Loaded aes256.js
Command Loaded avatar.js
Command Loaded deaes256.js
Command Loaded embed.js
Command Loaded enlarge.js
Command Loaded timer.js
Command Loaded translate.js
Command Loaded weather.js
Server is Ready!
loaded Event: disconnect.js
loaded Event: error.js
loaded Event: guildCreate.js
loaded Event: guildDelete.js
loaded Event: guildMemberAdd.js
loaded Event: message.js
loaded Event: messageDelete.js
loaded Event: ready.js
loaded Event: giveawayReactionAdded.js
loaded Event: giveawayReactionRemoved.js
loaded Event: addList.js
loaded Event: addSong.js
loaded Event: empty.js
loaded Event: error.js
loaded Event: initQueue.js
loaded Event: playList.js
loaded Event: playSong.js
loaded Event: searchCancel.js
loaded Event: searchResult.js
(node:3868) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\ZeGamer.c\Desktop\DraconianJSBot-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:133:26)
    at Client.login (C:\Users\ZeGamer.c\Desktop\DraconianJSBot-main\node_modules\discord.js\src\client\Client.js:223:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[DisTube] Downloaded youtube-dl 2021.04.17
(node:9940) UnhandledPromiseRejectionWarning: Error [SHARDING_READY_TIMEOUT]: Shard 0's Client took too long to become ready.
    at Timeout.onTimeout (C:\Users\ZeGamer.c\Desktop\DraconianJSBot-main\node_modules\discord.js\src\sharding\Shard.js:163:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

voici se qu'il y'a dans mon .env

{
    "token": "le token de mon bot"
}

**Comment by s4vrok** [comment]
.env file in this only ```TOKEN=(Your Token)```
