### ISSUE TITLE
Config.js Missing

### ISSUE THREAD

**Issue by wizcreations7** [ckt1031/DraconianBot#16]
For some reason, when I run `node shard.js` it can't seem to find `config.js`. I've checked myself, and it is not there. Was it miss-placed or what?

**Comment by cfmaniac** [comment]
Yes This does see to be missing, however I Found a Copy of config.js in the Releases Section:

{
	"prefix": "d!",
	"ownerID": "OWNER_ID",
	"everyoneMention": false,
	"hostedBy": true,
	"emoji": {
		"play": "▶️",
		"stop": "⏹️",
		"queue": "📄",
		"success": "☑️",
		"repeat": "🔁",
		"error": "❌"
	}
}

**Comment by wizcreations7** [comment]
Awesome man. I looked through a couple of previous releases but gave up aha. Thank you. Much appreciated.
