### ISSUE TITLE
Command Cooldown is not working

### ISSUE THREAD

**Issue by MathewAgustinB** [ckt1031/DraconianBot#20]
Go to: `events/client/message.js` line `30` code:
```js
	const cooldownAmount = (command.cooldown || 2) * 1000;
```
**Error:** Can't find `command.cooldown` that's why it goes `2 seconds` by default to all commands.

I tried adding this (example): 
```js
module.exports.help = {
	name: "help",
	description: "This command is used for displaying all commands.",
	usage: "p!help",
	accessableby: "Members",
	aliases: [],
	cooldown: 60 //1 Minutes or 60 Seconds
};
```
And still didn't work, there's a problem with the `command.cooldown`  can't find the value of `cooldown`.

**Comment by ckt1031** [comment]
Issue solved
