### ISSUE TITLE
Bot Script Enhancement and Maintaining

### ISSUE THREAD

**Issue by ckt1031** [ckt1031/DraconianBot#21]
- Enhancement
Since i have enough time to code bots in my free time, and the bot script contains many bugs and unstable issue. The bot script will be enhanced in the end of this month and fixing high memory usage when running the bot with global variables and unused features.

- v13 Updates
we have seen many bots are upgraded to discordjs v13 and user friendly for slash commands interactions. The bot will also follow the trend of discord javascript framework updates.

**Comment by CoperX-Dev** [comment]
@RealKoolisw Your bot is broken it doesn't see the prefix command

**Comment by CoperX-Dev** [comment]
In your bot does not work "serverinfo", "stats". Please fix these defects if it is not difficult for you. Thank you if you did.

**Comment by ghost** [comment]
@RealKoolisw In your bot does not work "serverinfo", "stats". Please fix these defects if it is not difficult for you. Thank you if you did.

**Comment by ckt1031** [comment]
All issues will be fixed early 2022
