### ISSUE TITLE
Please Read Please Reply

### ISSUE THREAD

**Issue by aesthetic-hanjisung** [ckt1031/DraconianBot#3]
It won't work for me

**Comment by ckt1031** [comment]
Okay

**Comment by ckt1031** [comment]
Tell me where u gonna to host or use commands over our official bot

**Comment by aesthetic-hanjisung** [comment]
My server

在 2021年1月26日週二 19:07，RealKoolisw <notifications@github.com> 寫道：

**Comment by aesthetic-hanjisung** [comment]
My Server

**Comment by ckt1031** [comment]
Issue totally fixed, i have reset the bot's database

**Comment by aesthetic-hanjisung** [comment]
Alright I have many emails and Discord messages to read
